            
CREATE USER IF NOT EXISTS TEST PASSWORD 'TEST' ADMIN;               
CREATE SCHEMA IF NOT EXISTS WORKSHOP AUTHORIZATION TEST;        

CREATE TABLE WORKSHOP.RATES(
    RATE_ID INT NOT NULL,
    CCY VARCHAR(10),
    XCCY VARCHAR(10),
    RATE FLOAT,
    XRATE FLOAT
);               
ALTER TABLE WORKSHOP.RATES ADD CONSTRAINT WORKSHOP.CONSTRAINT_4 PRIMARY KEY(RATE_ID);         
-- 10 +/- SELECT COUNT(*) FROM WORKSHOP.RATES;
INSERT INTO WORKSHOP.RATES(RATE_ID, CCY, XCCY, RATE, XRATE) VALUES(1, 'USD', 'EUR', 0.73649, 1.35778);        
INSERT INTO WORKSHOP.RATES(RATE_ID, CCY, XCCY, RATE, XRATE) VALUES(2, 'USD', 'GBP', 0.62176, 1.60834);        
INSERT INTO WORKSHOP.RATES(RATE_ID, CCY, XCCY, RATE, XRATE) VALUES(3, 'USD', 'INR', 61.8672, 0.01616);        
INSERT INTO WORKSHOP.RATES(RATE_ID, CCY, XCCY, RATE, XRATE) VALUES(4, 'EUR', 'USD', 1.35778, 0.73649);        
INSERT INTO WORKSHOP.RATES(RATE_ID, CCY, XCCY, RATE, XRATE) VALUES(5, 'EUR', 'GBP', 0.84415, 1.18462);        
INSERT INTO WORKSHOP.RATES(RATE_ID, CCY, XCCY, RATE, XRATE) VALUES(6, 'EUR', 'INR', 84.087, 0.01189);         
INSERT INTO WORKSHOP.RATES(RATE_ID, CCY, XCCY, RATE, XRATE) VALUES(7, 'GBP', 'EUR', 1.18462, 0.84415);        
INSERT INTO WORKSHOP.RATES(RATE_ID, CCY, XCCY, RATE, XRATE) VALUES(8, 'GBP', 'USD', 1.60834, 0.62176);        
INSERT INTO WORKSHOP.RATES(RATE_ID, CCY, XCCY, RATE, XRATE) VALUES(9, 'GBP', 'INR', 99.6219, 0.01004);        
INSERT INTO WORKSHOP.RATES(RATE_ID, CCY, XCCY, RATE, XRATE) VALUES(10, 'INR', 'SGD', 99.6219, 0.01004);       
